### PR TITLE
Added code blocks to README.md.

### PR DESCRIPTION
**Pull request by dreybuilds**
Adjusted last two lines for readability/accessibility .

### CODE REVIEW

**Comment by cypriansakwa** [comment]
Hi. I have not understood this email. Please explain since i am new here.

Thanks.

**Comment by dreybuilds** [comment]
Please check your github under "pull requests". I was reading through your repository and made a change to your README.md file.
 You are receiving this email because I am contributing to the repository and you have to approve the changes for them to reflect on your repository. The changes are in this PR(pull request)

**Comment by cypriansakwa** [comment]
Thanks. Who are you?

**Comment by cypriansakwa** [comment]
i cannot see your recommended change on my readme. needed to see it.

**Review by cypriansakwa — APPROVED** [review]

**Pull request merged**
